<?php

namespace Ribal\Onix\CodeList;

/**
 * ONIX Code List 196
 *
 * Used with <ProductFormFeatureValue> <b335>See List 79
 *
 * @see https://ns.editeur.org/onix/en/196
 */
class CodeList196 extends CodeList implements CodeListInterface
{
	/**
	 * Code List 196 for en
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/en/196
	 */
	protected static $en = [
		'00' => 'Accessibility summary',
		'01' => 'LIA Compliance Scheme',
		'02' => 'EPUB Accessibility Specification 1.0 A',
		'03' => 'EPUB Accessibility Specification 1.0 AA',
		'04' => 'Epub Accessibility Specification 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Unknown accessibility',
		'09' => 'Inaccessible, or known limited accessibility',
		'10' => 'No reading system accessibility options actively disabled (except)',
		'11' => 'Table of contents navigation',
		'12' => 'Index navigation',
		'13' => 'Single logical reading order',
		'14' => 'Short alternative textual descriptions',
		'15' => 'Full alternative textual descriptions',
		'16' => 'Visualised data also available as non-graphical data',
		'17' => 'Accessible math content as MathML',
		'18' => 'Accessible chemistry content as ChemML',
		'19' => 'Print-equivalent page numbering',
		'20' => 'Synchronised pre-recorded audio',
		'21' => 'Text-to-speech hinting provided',
		'22' => 'Language tagging provided',
		'24' => 'Dyslexia readability',
		'25' => 'Use of color is not sole means of conveying information',
		'26' => 'Use of high contrast between text and background color',
		'27' => 'Use of high contrast between foreground and background audio',
		'28' => 'Full alternative audio descriptions',
		'29' => 'Next / Previous structural navigation',
		'30' => 'ARIA roles provided',
		'31' => 'Accessible controls provided',
		'32' => 'Landmark navigation',
		'34' => 'Accessible chemistry content (as MathML)',
		'35' => 'Accessible math content (as LaTeX)',
		'36' => 'Appearance of all textual content can be modified',
		'37' => 'Use of ultra-high contrast between text foreground and background',
		'38' => 'Unusual words or abbreviations explained',
		'39' => 'Supplementary material to an audiobook is accessible',
		'40' => 'Link purposes clear',
		'41' => 'Page list navigation',
		'51' => 'All non-decorative content supports reading via pre-recorded audio',
		'52' => 'All non-decorative content supports reading without sight',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'EAA exception 1 – Micro-enterprises',
		'76' => 'EAA exception 2 – Disproportionate burden',
		'77' => 'EAA exception 3 – Fundamental alteration',
		'80' => 'WCAG v2.0',
		'81' => 'WCAG v2.1',
		'82' => 'WCAG v2.2',
		'84' => 'WCAG level A',
		'85' => 'WCAG level AA',
		'86' => 'WCAG level AAA',
		'90' => 'Compliance certification by (name)',
		'91' => 'Latest accessibility assessment date',
		'92' => 'Accessibility addendum',
		'93' => 'Compliance certification by (URL)',
		'94' => 'Compliance web page for detailed accessibility information',
		'95' => 'Trusted intermediary’s web page for detailed accessibility information',
		'96' => 'Publisher’s web page for detailed accessibility information',
		'97' => 'Compatibility tested',
		'98' => 'Trusted Intermediary contact',
		'99' => 'Publisher contact for further accessibility information',
	];

	/**
	 * Code List 196 for es
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/es/196
	 */
	protected static $es = [
		'00' => 'Resumen de accesibilidad',
		'01' => 'Esquema de conformidad LIA',
		'02' => 'Especificación de accesibilidad EPUB 1.0 A',
		'03' => 'Especificación de accesibilidad EPUB 1.0 AA',
		'04' => 'Accesibilidad Epub 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Accesibilidad desconocida',
		'09' => 'Inaccesible o se sabe que es de accesibilidad limitada',
		'10' => 'No está activamente desactivada ninguna opción de accesibilidad al sistema de lectura (Con excepciones)',
		'11' => 'Navegación en la tabla de contenidos',
		'12' => 'Índice navegable',
		'13' => 'Orden lógico de lectura único',
		'14' => 'Descripciones textuales alternativas cortas',
		'15' => 'Descripciones textuales alternativas completas',
		'16' => 'Visualizaciones de datos también disponibles en forma no gráfica',
		'17' => 'Contenido de notación matemática accesible como MathML',
		'18' => 'Contenido de notación química accesible como ChemML',
		'19' => 'Numeración de páginas equivalente a la de la versión impresa',
		'20' => 'Audio pregrabado sincronizado',
		'21' => 'Incluye pistas («hints») para la conversión de texto a voz',
		'22' => 'Incluye etiquetado de idioma',
		'24' => 'Legibilidad mejorada para personas con dislexia',
		'25' => 'Uso inclusivo del color',
		'26' => 'Uso inclusivo de contraste entre color de texto y fondo',
		'27' => 'Uso inclusivo del contraste en el volumen de audio',
		'28' => 'Descripciones de audio completas',
		'29' => 'Navegación estructural «Anterior / Siguiente»',
		'30' => 'Incluye roles ARIA',
		'31' => 'Incluye controles accesibles',
		'32' => 'Navegación por puntos de referencia',
		'34' => 'Contenido de notación química accesible (como MathML)',
		'35' => 'Contenido de notación matemática accesible (como LaTeX)',
		'36' => 'Todo el contenido textual se puede modificar',
		'37' => 'Uso de un contraste muy alto entre el primer plano del texto y el fondo',
		'38' => 'Explicación de palabras o abreviaturas poco usuales',
		'39' => 'El material complementario del audiolibro es accesible',
		'40' => 'Propósito de los enlaces explícito',
		'41' => 'Page list navigation',
		'51' => 'Todo el contenido «no decorativo» permite la lectura mediante audio pregrabado',
		'52' => 'Todo el contenido «no decorativo» admite la lectura sin visión',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'Entra en la exención 1 de la LEA – Microempresas',
		'76' => 'Entra en la exención 2 de la LEA – Carga desproporcionada',
		'77' => 'Entra en la exención 3 de la LEA – Modificación sustancial',
		'80' => 'Cumple WCAG v2.0',
		'81' => 'Cumple WCAG v2.1',
		'82' => 'Cumple WCAG v2.2',
		'84' => 'Cumple WCAG nivel A',
		'85' => 'Cumple WCAG nivel AA',
		'86' => 'Cumple WCAG nivel AAA',
		'90' => 'Certificación de cumplimiento por (nombre)',
		'91' => 'Fecha de la última evaluación de la accesibilidad',
		'92' => 'Apéndice de accesibilidad',
		'93' => 'Certificación de accesibilidad expedida por',
		'94' => 'Página web de certificación, con información detallada de accesibilidad',
		'95' => 'Página web de un intermediario de confianza, con información detallada de accesibilidad',
		'96' => 'Página web de la editorial, con información detallada de accesibilidad',
		'97' => 'Testeado para compatibilidad',
		'98' => 'Contacto de intermediario de confianza',
		'99' => 'Contacto en la editorial para más información sobre accesibilidad',
	];

	/**
	 * Code List 196 for de
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/de/196
	 */
	protected static $de = [
		'00' => 'Accessibility summary',
		'01' => 'LIA Compliance Scheme',
		'02' => 'EPUB Accessibility Specification 1.0 A',
		'03' => 'EPUB Accessibility Specification 1.0 AA',
		'04' => 'Epub Accessibility Specification 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Unknown accessibility',
		'09' => 'Inaccessible, or known limited accessibility',
		'10' => 'No reading system accessibility options actively disabled (except)',
		'11' => 'Table of contents navigation',
		'12' => 'Index navigation',
		'13' => 'Single logical reading order',
		'14' => 'Short alternative textual descriptions',
		'15' => 'Full alternative textual descriptions',
		'16' => 'Visualised data also available as non-graphical data',
		'17' => 'Accessible math content as MathML',
		'18' => 'Accessible chemistry content as ChemML',
		'19' => 'Print-equivalent page numbering',
		'20' => 'Synchronised pre-recorded audio',
		'21' => 'Text-to-speech hinting provided',
		'22' => 'Language tagging provided',
		'24' => 'Dyslexia readability',
		'25' => 'Use of color is not sole means of conveying information',
		'26' => 'Use of high contrast between text and background color',
		'27' => 'Use of high contrast between foreground and background audio',
		'28' => 'Full alternative audio descriptions',
		'29' => 'Next / Previous structural navigation',
		'30' => 'ARIA roles provided',
		'31' => 'Accessible controls provided',
		'32' => 'Landmark navigation',
		'34' => 'Accessible chemistry content (as MathML)',
		'35' => 'Accessible math content (as LaTeX)',
		'36' => 'Appearance of all textual content can be modified',
		'37' => 'Use of ultra-high contrast between text foreground and background',
		'38' => 'Unusual words or abbreviations explained',
		'39' => 'Supplementary material to an audiobook is accessible',
		'40' => 'Link purposes clear',
		'41' => 'Page list navigation',
		'51' => 'All non-decorative content supports reading via pre-recorded audio',
		'52' => 'All non-decorative content supports reading without sight',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'EAA exception 1 – Micro-enterprises',
		'76' => 'EAA exception 2 – Disproportionate burden',
		'77' => 'EAA exception 3 – Fundamental alteration',
		'80' => 'WCAG v2.0',
		'81' => 'WCAG v2.1',
		'82' => 'WCAG v2.2',
		'84' => 'WCAG level A',
		'85' => 'WCAG level AA',
		'86' => 'WCAG level AAA',
		'90' => 'Compliance certification by (name)',
		'91' => 'Latest accessibility assessment date',
		'92' => 'Accessibility addendum',
		'93' => 'Compliance certification by (URL)',
		'94' => 'Compliance web page for detailed accessibility information',
		'95' => 'Trusted intermediary’s web page for detailed accessibility information',
		'96' => 'Publisher’s web page for detailed accessibility information',
		'97' => 'Compatibility tested',
		'98' => 'Trusted Intermediary contact',
		'99' => 'Publisher contact for further accessibility information',
	];

	/**
	 * Code List 196 for fr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/fr/196
	 */
	protected static $fr = [
		'00' => 'Résumé sur l’accessibilité',
		'01' => 'Conforme aux instructions de la LIA (Libri Italiani Accessibili)',
		'02' => 'Spécifications d’accessibilité EPUB 1.0 A',
		'03' => 'Spécifications d’accessibilité EPUB 1.0 AA',
		'04' => 'Spécifications d’accessibilité EPUB 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Accessibilité inconnue',
		'09' => 'Inaccessible, ou accessibilité limitée connue',
		'10' => 'Aucune option d’accessibilité au système désactivée (exception)',
		'11' => 'Navigation dans la table des matières',
		'12' => 'Navigation dans l’index',
		'13' => 'Unique ordre de lecture logique',
		'14' => 'Brèves descriptions alternatives textuelles',
		'15' => 'Descriptions alternatives textuelles complètes',
		'16' => 'Représentations graphiques de données également accessibles comme données non graphiques',
		'17' => 'Contenu mathématique accessible comme MathML',
		'18' => 'Contenu chimique accessible comme ChemML',
		'19' => 'Numérotation de pages équivalente au document imprimé',
		'20' => 'Audio synchronisé préenregistré',
		'21' => 'Synthèse vocale optimisée',
		'22' => 'Balisage de la langue fourni',
		'24' => 'Lisibilité adaptée à la dyslexie',
		'25' => 'Usage de la couleur n’étant pas le seul moyen de transmettre l’information',
		'26' => 'Usage du contraste haut entre le texte et la couleur d’arrière-plan',
		'27' => 'Usage du contraste haut entre le contenu audio de premier plan et les bruits de fond',
		'28' => 'Audio-description alternative complète',
		'29' => 'Navigation structurelle suivant/précédent',
		'30' => 'Rôles ARIA fournis',
		'31' => 'Contrôles accessibles fournis',
		'32' => 'Repères de navigation',
		'34' => 'Accessibilité des contenus chimiques (comme MathML)',
		'35' => 'Accessibilité des contenus mathématiques (comme LaTeX)',
		'36' => 'L’apparence de tout le contenu textuel peut être modifiée',
		'37' => 'Utilisation d’un contraste ultra-élevé entre le texte et l’arrière-plan',
		'38' => 'Vocabulaire ou abréviations inhabituels expliqués',
		'39' => 'Accessibilité d’un matériel complémentaire à un livre audio',
		'40' => 'Fonctionnalité des liens',
		'41' => 'Navigation dans la liste des pages',
		'51' => 'Tout contenu non décoratif accessible aux utilisateurs via l’audio pré-enregistré',
		'52' => 'Tout contenu non décoratif accessible aux utilisateurs privés de la vue',
		'53' => 'Description du contenu mathématique',
		'54' => 'Contenu relatif à la chimie accessible (comme LaTeX)',
		'75' => 'Exception 1 EAA – micro-entreprises',
		'76' => 'Exception 2 EAA – charge disproportionnée',
		'77' => 'Exception 3 EAA – changement fondamental',
		'80' => 'WCAG v2.0',
		'81' => 'WCAG v2.1',
		'82' => 'WCAG v2.2',
		'84' => 'WCAG niveau A',
		'85' => 'WCAG niveau AA',
		'86' => 'WCAG niveau AAA',
		'90' => 'Certification de conformité par (nom)',
		'91' => 'Date de la dernière évaluation d’accessibilité',
		'92' => 'Addenda sur l’accessibilité',
		'93' => 'Certification de conformité par (URL)',
		'94' => 'Page web pour les informations détaillées d’accessibilité',
		'95' => 'Page web d’un intermédiaire approuvé pour les informations détaillées d’accessibilité',
		'96' => 'Page web de l’éditeur pour les informations détaillées d’accessibilité',
		'97' => 'Compatibilité testée',
		'98' => 'Contact intermédiaire approuvé',
		'99' => 'Contact éditeur pour informations complémentaires sur l’accessibilité',
	];

	/**
	 * Code List 196 for it
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/it/196
	 */
	protected static $it = [
		'00' => 'Riepilogo sull’accessibilità',
		'01' => 'Certificazione LIA',
		'02' => 'Specifiche di accessibilità EPUB 1.0 A',
		'03' => 'Specifiche di accessibilità EPUB 1.0 AA',
		'04' => 'Specifiche di accessibilità EPUB 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Accessibilità sconosciuta',
		'09' => 'Non accessibile, o con limiti noti all’accessibilità',
		'10' => 'Nessuna funzione di accessibilità del sistema di lettura attivamente disabilitata (con eccezioni)',
		'11' => 'Navigazione dell’indice dei contenuti',
		'12' => 'Navigazione dell’indice analitico',
		'13' => 'Ordine logico di lettura univoco',
		'14' => 'Descrizioni testuali alternative brevi',
		'15' => 'Descrizioni testuali alternative estese',
		'16' => 'Dati visualizzati disponibili anche come dati non grafici',
		'17' => 'Contenuto di matematica accessibile in formato MathML',
		'18' => 'Contenuto di chimica accessibile in formato ChemML',
		'19' => 'Numerazione delle pagine equivalente alla versione a stampa',
		'20' => 'Audio sincronizzato pre-registrato',
		'21' => 'Funzione di sintesi vocale inclusa',
		'22' => 'Funzione di riconoscimento della lingua inclusa',
		'24' => 'Leggibilità per dislessici',
		'25' => 'L’uso del colore non è l’unico mezzo per veicolare informazioni',
		'26' => 'Utilizzo di un elevato contrasto tra il colore del testo e dello sfondo',
		'27' => 'Utilizzo di un elevato contrasto tra l’audio in primo piano e di sottofondo',
		'28' => 'Descrizioni audio alternative complete',
		'29' => 'Navigazione strutturata successiva/precedente',
		'30' => 'Ruoli ARIA assegnati',
		'31' => 'Controlli accessibili presenti',
		'32' => 'Navigazione per punti di riferimento',
		'34' => 'Contenuti di chimica accessibili (in formato MathML)',
		'35' => 'Contenuti di matematica accessibili (in formato LaTeX)',
		'36' => 'La formattazione di tutto il contenuto testuale può essere modificata',
		'37' => 'Utilizzo di contrasto elevatissimo tra il colore del testo in primo piano e lo sfondo',
		'38' => 'Spiegazione di parole o abbreviazioni insolite',
		'39' => 'Il materiale di supporto all’audiolibro è accessibile',
		'40' => 'Lo scopo del link è chiaro',
		'41' => 'Page list navigation',
		'51' => 'Tutti i contenuti non decorativi supportano la lettura tramite audio preregistrato',
		'52' => 'Tutti i contenuti non decorativi supportano la lettura non visuale',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'Atto Europeo sull’Accessibilità – Eccezione 1: microimprese',
		'76' => 'Atto Europeo sull’Accessibilità – Eccezione 2: onere sproporzionato',
		'77' => 'Atto Europeo sull’Accessibilità – Eccezione 3: modifica sostanziale',
		'80' => 'WCAG v2.0',
		'81' => 'WCAG v2.1',
		'82' => 'WCAG v2.2',
		'84' => 'WCAG livello A',
		'85' => 'WCAG livello AA',
		'86' => 'WCAG livello AAA',
		'90' => 'Certificazione di conformità di (nome)',
		'91' => 'Data dell’ultima valutazione di accessibilità',
		'92' => 'Addendum sull’accessibilità',
		'93' => 'Certificazione di conformità di (URL)',
		'94' => 'Pagina internet con informazioni dettagliate sull’accessibilità',
		'95' => 'Pagina internet dell’intermediario accreditato con le informazioni sull’accessibilità',
		'96' => 'Pagina internet dell’editore con le informazioni sull’accessibilità',
		'97' => 'Esito verifica sulla compatibilità',
		'98' => 'Contatto dell’intermediario accreditato',
		'99' => 'Contatto dell’editore per ulteriori informazioni sull’accessibilità',
	];

	/**
	 * Code List 196 for nb
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/nb/196
	 */
	protected static $nb = [
		'00' => 'Tilgjengelighet, sammendrag',
		'01' => 'LIA Compliance Scheme',
		'02' => 'EPUB Tilgjengelighetsspesifikasjon 1.0 A',
		'03' => 'EPUB Tilgjengelighetsspesifikasjon 1.0 AA',
		'04' => 'EPUB Tilgjengelighetsspesifikasjon 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Ukjent tilgjengelighet',
		'09' => 'Utilgjengelig, eller begrenset tilgjengelighet',
		'10' => 'Ingen av lesesystemets funksjoner for tilgjengelighet er aktivt deaktivert (unntatt)',
		'11' => 'Innholdsfortegnelse med navigasjon',
		'12' => 'Register med navigasjon',
		'13' => 'Leserekkefølge',
		'14' => 'Korte alternative beskrivelser (tekst)',
		'15' => 'Fullstendige alternative beskrivelser (tekst)',
		'16' => 'Visuelle data er også tilgjengelig som ikke-grafisk data',
		'17' => 'Tilgjengelig matematisk innhold som MathML',
		'18' => 'Tilgjengelig kjemisk innhold som ChemML',
		'19' => 'Sidetall i tilsvarende trykt utgave',
		'20' => 'Synkronisert forhåndsinnspilt lyd',
		'21' => 'Tekst-til-tale er tilgjengelig',
		'22' => 'Språktagging er tilgjengelig',
		'24' => 'Dysleksi: lesbarhet',
		'25' => 'Bruk av farge',
		'26' => 'Bruk av høy kontrast mellom tekst og bakgrunnsfarge',
		'27' => 'Bruk av høy kontrast mellom forgrunns- og bakgrunnslyd',
		'28' => 'Komplette, alternative lydbeskrivelser',
		'29' => 'Neste / forrige strukturell navigasjon',
		'30' => 'ARIA-roller',
		'31' => 'Accessible controls provided',
		'32' => 'Landemerkenavigasjon',
		'34' => 'Tilgjengelig kjemisk innhold (som MathML)',
		'35' => 'Tilgjengelig matematisk innhold (som LaTeX)',
		'36' => 'Visning av alt tekstlig innhold kan endres',
		'37' => 'Bruk av svært høy kontrast mellom selve teksten og tekstens bakgrunn',
		'38' => 'Uvanlige ord eller forkortelser er forklart',
		'39' => 'Tilleggsinnhold til ei lydbok er tilgjengelig',
		'40' => 'Lenkers formål er tydelig',
		'41' => 'Page list navigation',
		'51' => 'Alt ikke-dekorativt innhold støtter lesing via forhåndsinnspilt lyd',
		'52' => 'Alt ikke-dekorativt innhold støtter lesing for ikke-seende',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'EAA unntak 1 – mikrobedrifter',
		'76' => 'EAA unntak 2 – uforholdsmessig stor belastning',
		'77' => 'EAA unntak 3 – grunnleggende endring',
		'80' => 'WCAG v 2.0',
		'81' => 'WCAG v 2.1',
		'82' => 'WCAG v 2.2',
		'84' => 'WCAG nivå A',
		'85' => 'WCAG nivå AA',
		'86' => 'WCAG nivå AAA',
		'90' => 'Oppfyllelse av krav – sertifisering av (navn)',
		'91' => 'Siste dato for tilgjengelighetsvurdering',
		'92' => 'Tilgjengelighetstillegg',
		'93' => 'Oppfyllelse av krav – sertifisering av (URL)',
		'94' => 'Nettside for detaljert tilgjengelighetsinformasjon',
		'95' => 'Nettside for detaljert tilgjengelighetsinformasjon, fra en pålitelig tredjepart',
		'96' => 'Utgivers nettside for detaljert tilgjengelighetsinformasjon',
		'97' => 'Testet for kompatibilitet',
		'98' => 'Kontaktinformasjon til en pålitelig tredjepart',
		'99' => 'Kontaktinformasjon til utgiver for ytterligere informasjon om tilgjengelighet',
	];

	/**
	 * Code List 196 for tr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/tr/196
	 */
	protected static $tr = [
		'00' => 'Erişilebilirlik özeti',
		'01' => 'LIA Uyumluluk Düzeni',
		'02' => 'Erişilebilirlik Spesifikasyonu 1.0 A',
		'03' => 'Erişilebilirlik Spesifikasyonu 1.0 AA',
		'04' => 'Epub Accessibility Specification 1.1',
		'05' => 'PDF/UA-1',
		'06' => 'PDF/UA-2',
		'08' => 'Unknown accessibility',
		'09' => 'Erişim dışı',
		'10' => 'Hiçbir okuyucu sistemi erişilebilirlik seçeneği geçersizkılınmamıştır (istisna)',
		'11' => 'İçindekiler tablosu gezintisi',
		'12' => 'Dizin gezintisi',
		'13' => 'Okuma düzeni',
		'14' => 'Kısa alternatif tanımlar',
		'15' => 'Tam alternatif tanımlar',
		'16' => 'Görselleştirilmiş veri grafik olmayan veri olarak da mevcut',
		'17' => 'Erişilebilir matematiksel içerik',
		'18' => 'Erişilebilir kimyasal içerik',
		'19' => 'Basılı eşdeğeri sayfa numaralandırma',
		'20' => 'Senkronize ön kayıtlı işitsel',
		'21' => 'Metin okuma desteği var',
		'22' => 'Dil etiketleme var',
		'24' => 'Disleksi okunabilirliği',
		'25' => 'Use of color is not sole means of conveying information',
		'26' => 'Use of high contrast between text and background color',
		'27' => 'Use of high contrast between foreground and background audio',
		'28' => 'Full alternative audio descriptions',
		'29' => 'Next / Previous structural navigation',
		'30' => 'ARIA roles provided',
		'31' => 'Accessible controls provided',
		'32' => 'Landmark navigation',
		'34' => 'Accessible chemistry content (as MathML)',
		'35' => 'Accessible math content (as LaTeX)',
		'36' => 'Appearance of all textual content can be modified',
		'37' => 'Use of ultra-high contrast between text foreground and background',
		'38' => 'Unusual words or abbreviations explained',
		'39' => 'Supplementary material to an audiobook is accessible',
		'40' => 'Link purposes clear',
		'41' => 'Page list navigation',
		'51' => 'All non-decorative content supports reading via pre-recorded audio',
		'52' => 'All non-decorative content supports reading without sight',
		'53' => 'Described math content',
		'54' => 'Accessible chemistry content (as LaTeX)',
		'75' => 'EAA exception 1 – Micro-enterprises',
		'76' => 'EAA exception 2 – Disproportionate burden',
		'77' => 'EAA exception 3 – Fundamental alteration',
		'80' => 'WCAG v2.0',
		'81' => 'WCAG v2.1',
		'82' => 'WCAG v2.2',
		'84' => 'WCAG level A',
		'85' => 'WCAG level AA',
		'86' => 'WCAG level AAA',
		'90' => 'Compliance certification by (name)',
		'91' => 'Latest accessibility assessment date',
		'92' => 'Accessibility addendum',
		'93' => 'Compliance certification by (URL)',
		'94' => 'Ayrıntılı erişilebilirlik bilgileri için uygunluk web sayfası',
		'95' => 'Ayrıntılı erişilebilirlik bilgileri için güvenilir aracı kuruluşun web sayfası',
		'96' => 'Ayrıntılı erişilebilirlik bilgileri için yayımcının web sayfası',
		'97' => 'Uyumluluk test edildi',
		'98' => 'Güvenilir aracı ilişki',
		'99' => 'Daha fazla erişilebilirlik bilgisi için yayımcı ilişkisi',
	];
}
