<?php

namespace Ribal\Onix\CodeList;

/**
 * ONIX Code List 83
 *
 * Used with <BibleVersion> <b353>
 *
 * @see https://ns.editeur.org/onix/en/83
 */
class CodeList83 extends CodeList implements CodeListInterface
{
	/**
	 * Code List 83 for en
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/en/83
	 */
	protected static $en = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Amplified',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano – UTET',
		'GRK' => 'Original Greek',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Original Hebrew',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, Updated',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Other',
	];

	/**
	 * Code List 83 for es
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/es/83
	 */
	protected static $es = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Amplified',
		'ANM' => 'Antonio Marini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'C.E.I. – Conferenza Episcopale Italiana',
		'CEN' => 'C.E.I. – Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano',
		'GRK' => 'Original Greek',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Original Hebrew',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, Updated',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traducción Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Día',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Other',
	];

	/**
	 * Code List 83 for de
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/de/83
	 */
	protected static $de = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Amplified',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano – UTET',
		'GRK' => 'Original Greek',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Original Hebrew',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, Updated',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Other',
	];

	/**
	 * Code List 83 for fr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/fr/83
	 */
	protected static $fr = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Amplified',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'Godʼs Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano – UTET',
		'GRK' => 'Grec original',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Hébreu original',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Childrenʼs',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jérusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Readerʼs',
		'NJB' => 'Nouvelle Bible de Jérusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'Nouveau Testament en anglais moderne (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Todayʼs English',
		'TNI' => 'Todayʼs New International',
		'ZZZ' => 'Autre',
	];

	/**
	 * Code List 83 for it
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/it/83
	 */
	protected static $it = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Ampliata',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano – UTET',
		'GRK' => 'Originale Greco',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Originale Ebraico',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, aggiornata',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Altre',
	];

	/**
	 * Code List 83 for nb
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/nb/83
	 */
	protected static $nb = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Amplified',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano',
		'GRK' => 'Original Greek',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Original Hebrew',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, Updated',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Other',
	];

	/**
	 * Code List 83 for tr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/tr/83
	 */
	protected static $tr = [
		'ALV' => 'Alberto Vaccari',
		'AMP' => 'Genişletilmiş',
		'ANM' => 'Antonio Martini',
		'ASV' => 'American Standard',
		'CEB' => 'Common English Bible',
		'CEI' => 'Conferenza Episcopale Italiana',
		'CEN' => 'Conferenza Episcopale Italiana 2008',
		'CEV' => 'Contemporary English',
		'CNC' => 'Concordata',
		'DDI' => 'Diodati',
		'DDN' => 'Nuova Diodati',
		'DOU' => 'Douay-Rheims',
		'EIN' => 'Einheitsübersetzung',
		'ESV' => 'English Standard',
		'FBB' => 'Biblia (1776)',
		'FRA' => 'Raamattu (1933/1938)',
		'FRK' => 'Raamattu kansalle',
		'FRM' => 'Raamattu (1992)',
		'GDW' => 'God’s Word',
		'GEN' => 'Geneva',
		'GNB' => 'Good News',
		'GPR' => 'Galbiati, Penna, Rossano – UTET',
		'GRK' => 'Original Greek',
		'GRM' => 'Garofano, Rinaldi – Marietti',
		'HBR' => 'Original Hebrew',
		'HCS' => 'Holman Christian Standard',
		'ICB' => 'International Children’s',
		'ILC' => 'Traduzione Interconfessionale in Lingua Corrente',
		'JER' => 'Jerusalem',
		'KJV' => 'King James',
		'KJT' => '21st Century King James',
		'LVB' => 'Living Bible',
		'LZZ' => 'Luzzi',
		'MSG' => 'Message Bible',
		'NAB' => 'New American',
		'NAS' => 'New American Standard',
		'NAU' => 'New American Standard, Updated',
		'NBA' => 'Bibelen 1895',
		'NBB' => 'Bibelen 1930',
		'NBC' => 'Bibelen 1938',
		'NBD' => 'Bibelen 1978-85',
		'NBE' => 'Bibelen 1978',
		'NBF' => 'Bibelen 1985',
		'NBG' => 'Bibelen 1988',
		'NBH' => 'Bibelen 1978-85/rev. 2005',
		'NBI' => 'Bibelen 2011',
		'NCV' => 'New Century',
		'NEB' => 'New English',
		'NGO' => 'Bibelen Guds ord',
		'NIV' => 'New International',
		'NIR' => 'New International Reader’s',
		'NJB' => 'New Jerusalem',
		'NKJ' => 'New King James',
		'NNK' => 'Bibelen, nynorsk',
		'NLV' => 'New Living',
		'NRS' => 'New Revised Standard',
		'NTV' => 'Nueva Traduccion Vivienta',
		'NVB' => 'Novissima Versione della Bibbia',
		'NVD' => 'Nueva Biblia al Dia',
		'NVI' => 'Nueva Version Internacional',
		'PHP' => 'New Testament in Modern English (Phillips)',
		'REB' => 'Revised English',
		'REV' => 'Revised Version',
		'RSV' => 'Revised Standard',
		'RVL' => 'Reina Valera',
		'SBB' => 'Bibel 2000',
		'SMK' => 'Bibelen, samisk',
		'TEV' => 'Today’s English',
		'TNI' => 'Today’s New International',
		'ZZZ' => 'Diğer',
	];
}
