<?php

namespace Ribal\Onix\CodeList;

/**
 * ONIX Code List 79
 *
 * Used with <ProductFormFeatureType> <b334>
 *
 * @see https://ns.editeur.org/onix/en/79
 */
class CodeList79 extends CodeList implements CodeListInterface
{
	/**
	 * Code List 79 for en
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/en/79
	 */
	protected static $en = [
		'01' => 'Color of cover',
		'26' => 'Color of spine',
		'27' => 'Color of foil',
		'02' => 'Color of page edges',
		'55' => 'Color of endpapers',
		'03' => 'Text font',
		'04' => 'Special cover material',
		'05' => 'DVD region',
		'06' => 'Operating system requirements',
		'07' => 'Other system requirements',
		'08' => '‘Point and listen’ device compatibility',
		'09' => 'E-publication accessibility detail',
		'10' => 'E-publication format version',
		'12' => 'US CPSIA or other international hazard warning',
		'13' => 'EU General Product Safety Regulation and Toy Safety Directive hazard warning',
		'14' => 'IATA Dangerous Goods warning',
		'15' => 'E-publication format version code',
		'16' => 'E-publication format validator version',
		'17' => '‘Point and watch’ device/app compatibility',
		'18' => 'E-publication authentication and access control',
		'19' => 'Battery type and safety',
		'20' => 'Battery capacity',
		'21' => 'Dangerous goods',
		'22' => 'Game pieces',
		'23' => 'Game players',
		'24' => 'Game play time',
		'25' => 'Personal data requirements',
		'30' => 'Not FSC or PEFC certified',
		'31' => 'FSC certified – pure',
		'32' => 'FSC certified – mixed sources',
		'33' => 'FSC certified – recycled',
		'34' => 'PEFC certified',
		'35' => 'PEFC recycled',
		'36' => 'FSC or PEFC certified Pre- and Post-Consumer Waste (PCW) percentage',
		'37' => 'Claimed Pre- and Post-Consumer Waste (PCW) percentage',
		'38' => '‘Green’ inks',
		'39' => '‘Green’ adhesives',
		'40' => 'Paper produced by ‘green’ technology',
		'41' => 'Carbon/GHG emission certification scheme',
		'42' => 'Carbon/GHG emission certification / license number',
		'43' => 'Carbon/GHG emission certification URL',
		'44' => 'Carbon/GHG Scope 3 certified Carbon dioxide equivalent emission',
		'45' => 'Carbon/GHG Scope 2 certified Carbon dioxide equivalent emission',
		'46' => 'Carbon/GHG Scope 1 certified Carbon dioxide equivalent emission',
		'47' => 'EUDR raw material location (interior or full product)',
		'48' => 'EUDR raw material location (binding)',
		'49' => 'EUDR raw material location (other)',
		'50' => 'EUDR due diligence reference',
		'51' => 'EUDR associated due diligence references',
		'52' => 'EUDR compliant with national law attestation',
		'53' => 'EUDR deforestation-free attestation',
		'54' => 'EUDR stock present attestation',
	];

	/**
	 * Code List 79 for es
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/es/79
	 */
	protected static $es = [
		'01' => 'Color de cubierta',
		'26' => 'Color del lomo',
		'27' => 'Color de la lámina metálica',
		'02' => 'Color de los cantos',
		'55' => 'Color of endpapers',
		'03' => 'Fuente del texto',
		'04' => 'Material especial de la cubierta',
		'05' => 'Región DVD',
		'06' => 'Requerimientos del sistema operativo',
		'07' => 'Otros requisitos del sistema',
		'08' => 'Compatibilidad con dispositivos o aplicaciones «Point and listen» («Apuntar y escuchar»)',
		'09' => 'Detalle de accesibilidad para publicación digital',
		'10' => 'Versión del formato para una publicación digital',
		'12' => 'Aviso de riesgo (CPSIA u otros avisos en EE. UU.)',
		'13' => 'Aviso de riesgo de seguridad de juguetes (UE)',
		'14' => 'Aviso de Mercancía Peligrosa para la IATA',
		'15' => 'Código de versión de formato para publicación digital',
		'16' => 'Versión del validador de formato de publicación digital',
		'17' => 'Compatibilidad con dispositivos o aplicaciones «Point and watch («Apuntar y mirar»)',
		'18' => 'Control de autenticación y acceso para publicación digital',
		'19' => 'Tipo de batería',
		'20' => 'Capacidad de la batería',
		'21' => 'Mercancía peligrosa',
		'22' => 'Piezas de un juego',
		'23' => 'Jugadores de un juego',
		'24' => 'Tiempo de juego',
		'25' => 'Requisitos de datos personales',
		'30' => 'Sin certificación FSC o PEFC',
		'31' => 'Certificado FSC – puro',
		'32' => 'Certificado FSC – fuentes mixtas',
		'33' => 'Certificado FSC – reciclado',
		'34' => 'Certificado PEFC',
		'35' => 'Reciclado PEFC',
		'36' => 'Porcentaje de PCW («Post Consumer Waste») certificado por FSC o PEFC',
		'37' => 'Porcentaje declarado de PCW («Post Consumer Waste»)',
		'38' => 'Tintas «verdes»',
		'39' => 'Adhesivos «verdes»',
		'40' => 'Papel elaborado con tecnologías «verdes»',
		'41' => 'Sistema de certificación de emisiones de CO2 / GHG',
		'42' => 'Certificación de emisiones de CO2 / GHG / número de licencia',
		'43' => 'URL de certificación de emisiones de CO2 / GHG',
		'44' => 'Emisión equivalente certificada de CO2 (Alcance 3)',
		'45' => 'Emisión equivalente certificada de CO2 (Alcance 2)',
		'46' => 'Emisión equivalente certificada de CO2 (Alcance 1)',
		'47' => 'Ubicación original de la materia prima: Interior o todo el conjunto (EUDR)',
		'48' => 'Ubicación original de la materia prima: Encuadernación (EUDR)',
		'49' => 'Ubicación original de la materia prima del libro: Otros usos (EUDR)',
		'50' => 'Referencia de la declaración de diligencia debida (EUDR)',
		'51' => 'Referencias de diligencia debida asociadas a EUDR',
		'52' => 'Declaración de conformidad con la legislación nacional para EUDR',
		'53' => 'Declaración de deforestación libre para EUDR',
		'54' => 'Declaración sobre existencias previas para EUDR',
	];

	/**
	 * Code List 79 for de
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/de/79
	 */
	protected static $de = [
		'01' => 'Color of cover',
		'26' => 'Color of spine',
		'27' => 'Color of foil',
		'02' => 'Color of page edges',
		'55' => 'Color of endpapers',
		'03' => 'Text font',
		'04' => 'Special cover material',
		'05' => 'DVD region',
		'06' => 'Operating system requirements',
		'07' => 'Other system requirements',
		'08' => '‘Point and listen’ device compatibility',
		'09' => 'E-publication accessibility detail',
		'10' => 'E-publication format version',
		'12' => 'US CPSIA or other international hazard warning',
		'13' => 'EU General Product Safety Regulation and Toy Safety Directive hazard warning',
		'14' => 'IATA Dangerous Goods warning',
		'15' => 'E-publication format version code',
		'16' => 'E-publication format validator version',
		'17' => '‘Point and watch’ device/app compatibility',
		'18' => 'E-publication authentication and access control',
		'19' => 'Battery type and safety',
		'20' => 'Battery capacity',
		'21' => 'Dangerous goods',
		'22' => 'Game pieces',
		'23' => 'Game players',
		'24' => 'Game play time',
		'25' => 'Personal data requirements',
		'30' => 'Not FSC or PEFC certified',
		'31' => 'FSC certified – pure',
		'32' => 'FSC certified – mixed sources',
		'33' => 'FSC certified – recycled',
		'34' => 'PEFC certified',
		'35' => 'PEFC recycled',
		'36' => 'FSC or PEFC certified Pre- and Post-Consumer Waste (PCW) percentage',
		'37' => 'Claimed Pre- and Post-Consumer Waste (PCW) percentage',
		'38' => '‘Green’ inks',
		'39' => '‘Green’ adhesives',
		'40' => 'Paper produced by ‘green’ technology',
		'41' => 'Carbon/GHG emission certification scheme',
		'42' => 'Carbon/GHG emission certification / license number',
		'43' => 'Carbon/GHG emission certification URL',
		'44' => 'Carbon/GHG Scope 3 certified Carbon dioxide equivalent emission',
		'45' => 'Carbon/GHG Scope 2 certified Carbon dioxide equivalent emission',
		'46' => 'Carbon/GHG Scope 1 certified Carbon dioxide equivalent emission',
		'47' => 'EUDR raw material location (interior or full product)',
		'48' => 'EUDR raw material location (binding)',
		'49' => 'EUDR raw material location (other)',
		'50' => 'EUDR due diligence reference',
		'51' => 'EUDR associated due diligence references',
		'52' => 'EUDR compliant with national law attestation',
		'53' => 'EUDR deforestation-free attestation',
		'54' => 'EUDR stock present attestation',
	];

	/**
	 * Code List 79 for fr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/fr/79
	 */
	protected static $fr = [
		'01' => 'Couleur de couverture',
		'26' => 'Couleur du dos',
		'27' => 'Couleur de dorure à la presse',
		'02' => 'Couleur des tranches',
		'55' => 'Couleur des pages de garde',
		'03' => 'Police de caractères',
		'04' => 'Matériau spécial de couverture',
		'05' => 'Région DVD',
		'06' => 'Configuration requise du système d’exploitation',
		'07' => 'Autre configuration système requise',
		'08' => 'Compatibilité avec le dispositif « Point and listen »',
		'09' => 'Détail d’accessibilité de publication numérique',
		'10' => 'Version du format de publication numérique',
		'12' => 'Avertissement CPSIA ou autre avertissement sur les risques (Etats-Unis)',
		'13' => 'Règlement général sur la sécurité des produits et Directive relative à la sécurité des jouets (UE)',
		'14' => 'Avertissement sur les articles dangereux (IATA)',
		'15' => 'Code de version du format de publication numérique',
		'16' => 'Version du validateur du format de publication numérique',
		'17' => 'Compatibilité avec le dispositif/app « Point and watch »',
		'18' => 'Authentification et contrôle d’accès à la publication numérique',
		'19' => 'Type de batterie et sécurité',
		'20' => 'Capacité de la batterie',
		'21' => 'Articles dangereux',
		'22' => 'Pièces de jeu',
		'23' => 'Joueurs',
		'24' => 'Temps de jeu',
		'25' => 'Niveau de protection des données personnelles',
		'30' => 'Non certifié FSC ou PEFC',
		'31' => 'Certification FSC Pur',
		'32' => 'Certifié FSC – sources mixtes',
		'33' => 'Certification FSC – Recyclé',
		'34' => 'Certifié PEFC',
		'35' => 'Recyclé PEFC',
		'36' => 'Certifié FSC ou PEFC – Pourcentage PCW (Post-Consumer-Waste)',
		'37' => 'Pourcentage PCW (Pre-Consumer Waste et Post-Consumer Waste) déclaré',
		'38' => 'Encres « vertes »',
		'39' => 'Adhésifs « verts »',
		'40' => 'Papier produit selon les technologies « vertes »',
		'41' => 'Système de certification des émissions de carbone/GES',
		'42' => 'Certification des émissions de carbone/GES – Numéro de licence',
		'43' => 'URL de certification des émissions de carbone/GES',
		'44' => 'Emissions de carbone/GES – Champ d’application 3 Equivalent d’émission de dioxyde de carbone',
		'45' => 'Emissions de carbone/GES – Champ d’application 2 Equivalent d’émission de dioxyde de carbone',
		'46' => 'Emissions de carbone/GES – Champ d’application 1 Equivalent d’émission de dioxyde de carbone',
		'47' => 'Lieu d’origine des matières premières RDUE (intérieur ou produit complet)',
		'48' => 'Lieu d’origine des matières premières RDUE (reliure)',
		'49' => 'Lieu d’origine des matières premières RDUE (autres éléments)',
		'50' => 'Déclaration de diligence raisonnée RDUE',
		'51' => 'Références de déclaration de diligence raisonnée associées à RDUE',
		'52' => 'RDUE conforme à la législation nationale',
		'53' => 'Attestation de non-déforestation RDUE',
		'54' => 'Attestation de présence des stocks RDUE',
	];

	/**
	 * Code List 79 for it
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/it/79
	 */
	protected static $it = [
		'01' => 'Colore della copertina',
		'26' => 'Colore del dorso',
		'27' => 'Colore della lamina',
		'02' => 'Colore del bordo pagina',
		'55' => 'Color of endpapers',
		'03' => 'Carattere del testo',
		'04' => 'Copertina in materiale speciale',
		'05' => 'Regione DVD',
		'06' => 'Requisiti del sistema operativo',
		'07' => 'Altri requisiti di sistema',
		'08' => 'Compatibilità con dispositivo di applicazione «point and listen»',
		'09' => 'Accessibilità della pubblicazione elettronica',
		'10' => 'Versione del formato della pubblicazione elettronica',
		'12' => 'CPSIA o altre avvertenze sulla pericolosità negli Stati Uniti',
		'13' => 'Avvertenza sulla sicurezza dei giocattoli (Europa)',
		'14' => 'IATA Dangerous Goods warning',
		'15' => 'Codice della versione del formato della pubblicazione elettronica',
		'16' => 'Versione del validatore del formato della pubblicazione elettronica',
		'17' => 'Compatibilità con dispositivo o applicazione «point and watch»',
		'18' => 'Autenticazione e controllo dell’accesso alla pubblicazione elettronica',
		'19' => 'Tipo di batteria e sicurezza',
		'20' => 'Capacità della batteria',
		'21' => 'Merci pericolose',
		'22' => 'Pezzi del gioco',
		'23' => 'Giocatori',
		'24' => 'Durata del gioco',
		'25' => 'Dati personali richiesti',
		'30' => 'Senza etichetta FSC o PEFC',
		'31' => 'Etichetta FSC – puro',
		'32' => 'Etichetta FSC – misto',
		'33' => 'Etichetta FSC – riciclato',
		'34' => 'Etichetta PEFC',
		'35' => 'Etichetta PEFC riciclato',
		'36' => 'Percentuale di scarti pre e post consumo (PCW) su etichette FSC o PEFC',
		'37' => 'Percentuale di scarti pre e post consumo (PCW) dichiarata',
		'38' => 'Inchiostri ecocompatibili',
		'39' => 'Collanti ecocompatibili',
		'40' => 'Carta prodotta con tecnologia ecocompatibile',
		'41' => 'Schema di certificazione delle emissioni di carbonio/gas ad effetto serra',
		'42' => 'Numero di licenza della certificazione delle emissioni di carbonio/gas ad effetto serra',
		'43' => 'Url della certificazione delle emissioni di carbonio/gas ad effetto serra',
		'44' => 'Emissione equivalente di anidride carbonica basata sulla certificazione delle emissioni di carbonio/gas ad effetto serra Scope 3',
		'45' => 'Emissione equivalente di anidride carbonica basata sulla certificazione delle emissioni di carbonio/gas ad effetto serra Scope 2',
		'46' => 'Emissione equivalente di anidride carbonica basata sulla certificazione delle emissioni di carbonio/gas ad effetto serra Scope 1',
		'47' => 'Ubicazione EUDR delle materie prime (interno del prodotto o prodotto completo)',
		'48' => 'Ubicazione EUDR delle materie prime (rilegatura)',
		'49' => 'Ubicazione EUDR delle materie prime (altro)',
		'50' => 'Riferimento alla dichiarazione di due diligence EUDR',
		'51' => 'Riferimenti a dichiarazioni di due diligence EUDR associate',
		'52' => 'Attestazione EUDR di conformità alla legislazione nazionale',
		'53' => 'Attestazione EUDR di deforestazione zero',
		'54' => 'Attestazione EUDR sui prodotti attualmente a magazzino',
	];

	/**
	 * Code List 79 for nb
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/nb/79
	 */
	protected static $nb = [
		'01' => 'Innbindingsfarge',
		'26' => 'Ryggfarge',
		'27' => 'Foliefarge',
		'02' => 'Papirkantfarge',
		'55' => 'Color of endpapers',
		'03' => 'Typesnitt',
		'04' => 'Spesielt innbindingsmateriale',
		'05' => 'DVD-regioner',
		'06' => 'Krav til operativsystem',
		'07' => 'Andre systemkrav',
		'08' => 'Kompatibilitet til ‘Pek og hør’-enheter',
		'09' => 'E-publikasjoner, tilgjengelighetsdetaljer',
		'10' => 'E-publikasjoner, formatversjon',
		'12' => 'CPSIA or other US hazard warning',
		'13' => 'EU General Product Safety Regulation and Toy Safety Directive hazard warning',
		'14' => 'IATA Dangerous Goods warning',
		'15' => 'E-publikasjoner, kode for formatversjon',
		'16' => 'E-publikasjoner, versjon for formatvalidator',
		'17' => 'Kompatibilitet til ‘Pek og se’-enheter/apper',
		'18' => 'Autentiserings- og tilgangskontroll for epublikasjoner',
		'19' => 'Batteritype',
		'20' => 'Batterikapasitet',
		'21' => 'Farlig gods',
		'22' => 'Spillbrikker',
		'23' => 'Spilldeltakere',
		'24' => 'Spilletid',
		'25' => 'Krav til personopplysninger',
		'30' => 'Ikke FSC- eller PEFC-sertifisert',
		'31' => 'FSC certified – pure',
		'32' => 'FSC certified – mixed sources',
		'33' => 'FSC certified – recycled',
		'34' => 'PEFC certified',
		'35' => 'PEFC recycled',
		'36' => 'FSC or PEFC certified Pre- and Post-Consumer Waste (PCW) percentage',
		'37' => 'Claimed Pre- and Post-Consumer Waste (PCW) percentage',
		'38' => '‘Grønt’ blekk',
		'39' => '‘Grønt’ lim',
		'40' => 'Papir produsert ved bruk av ‘grønn’ teknologi',
		'41' => 'Carbon/GHG emission certification scheme',
		'42' => 'Carbon/GHG emission certification / license number',
		'43' => 'Carbon/GHG emission certification URL',
		'44' => 'Carbon/GHG Scope 3 certified Carbon dioxide equivalent emission',
		'45' => 'Carbon/GHG Scope 2 certified Carbon dioxide equivalent emission',
		'46' => 'Carbon/GHG Scope 1 certified Carbon dioxide equivalent emission',
		'47' => 'EUDR råvarelokasjon (innmat eller hele produktet)',
		'48' => 'EUDR råvarelokasjon (innbinding)',
		'49' => 'EUDR råvarelokasjon (annet)',
		'50' => 'EUDR due diligence referanse',
		'51' => 'EUDR-tilknyttede DDS-referanser',
		'52' => 'EUDR som er i henhold til nasjonal lovgivning',
		'53' => 'EUDR attestasjon av avskogningsfri produksjon',
		'54' => 'EUDR attestasjon av lagerbeholdning',
	];

	/**
	 * Code List 79 for tr
	 *
	 * @var array
	 * @see https://ns.editeur.org/onix/tr/79
	 */
	protected static $tr = [
		'01' => 'Kapak rengi',
		'26' => 'Color of spine',
		'27' => 'Color of foil',
		'02' => 'Sayfa kenarı rengi',
		'55' => 'Color of endpapers',
		'03' => 'Metin yazı karakteri',
		'04' => 'Özel kapak malzemesi',
		'05' => 'DVD bölgesi',
		'06' => 'İşletim sistemi gereksinimleri',
		'07' => 'Diğer sistem gereksinimleri',
		'08' => '‘Seç-dinle’ aygıt/program uyumluluğu',
		'09' => 'E-yayın erişim bilgileri',
		'10' => 'E-yayın format sürümü',
		'12' => 'CPSIA boğulma tehlikesi uyarısı',
		'13' => 'AB Oyuncak Güvenliği Tehlike Uyarısı',
		'14' => 'IATA Tehlikeli Maddeler uyarısı',
		'15' => 'E-yayın format sürümü kodu',
		'16' => 'E-publication format validator version',
		'17' => '‘Seç-izle’ aygıt/program uyumluluğu',
		'18' => 'E-publication authentication and access control',
		'19' => 'Battery type and safety',
		'20' => 'Battery capacity',
		'21' => 'Dangerous goods',
		'22' => 'Game pieces',
		'23' => 'Game players',
		'24' => 'Game play time',
		'25' => 'Personal data requirements',
		'30' => 'FSC ya da PEFC onaylı değil',
		'31' => 'FSC onaylı – saf',
		'32' => 'FSC onaylı – karışık kaynak',
		'33' => 'FSC onaylı – geri kazanılmış',
		'34' => 'PEFC onaylı',
		'35' => 'PEFC geri kazanılmış',
		'36' => 'FSC ya da PEFC onaylı Geri Dönüşüm ve Tüketici Atıkları (PCW) yüzdesi',
		'37' => 'Beyan edilen Geri Dönüşüm ve Tüketici Atıkları (PCW) yüzdesi',
		'38' => '‘Green’ inks',
		'39' => '‘Green’ adhesives',
		'40' => '‘Yeşil’ teknoloji ile üretilmiş kağıt',
		'41' => 'Carbon/GHG emission certification scheme',
		'42' => 'Carbon/GHG emission certification / license number',
		'43' => 'Carbon/GHG emission certification URL',
		'44' => 'Carbon/GHG Scope 3 certified Carbon dioxide equivalent emission',
		'45' => 'Carbon/GHG Scope 2 certified Carbon dioxide equivalent emission',
		'46' => 'Carbon/GHG Scope 1 certified Carbon dioxide equivalent emission',
		'47' => 'EUDR raw material location (interior or full product)',
		'48' => 'EUDR raw material location (binding)',
		'49' => 'EUDR raw material location (other)',
		'50' => 'EUDR due diligence reference',
		'51' => 'EUDR associated due diligence references',
		'52' => 'EUDR compliant with national law attestation',
		'53' => 'EUDR deforestation-free attestation',
		'54' => 'EUDR stock present attestation',
	];
}
